# Generated by Django 4.1.3 on 2022-12-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
